name: Nightly jobs

# Trigger the workflow with UTC time using cron syntax
on:
  schedule:
    # - cron: "*/5 * * * *" # every 5 minutes FOR_TESTING
    - cron: "0 7 * * *" # 10pm USA Central Time every day

jobs:
  test:
    name: Testing and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - run: corepack enable
      - run: yarn install
      - run: yarn test:lint:pipeline
      - run: yarn test:unit:pipeline
      - run: yarn cy:run:pipeline

      # Always try to upload artifacts, even if Cypress fails
      - name: Upload Cypress diff_output
        if: always() # ensures diff_output get uploaded on failure
        uses: actions/upload-artifact@v4
        with:
          name: cypress-diff_output
          path: cypress/diff_output

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
