name: Create release

on:
  push:
    tags:
      - "v*" # Trigger on any tag starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo="${{ github.repository }}" \
            --title="${{ github.repository_name }} ${{ github.ref_name }}" \
            --generate-notes
